### ISSUE TITLE
Create integration test to verify all methods of client

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-client#12]

**Comment by siddharthashw** [comment]
Already created https://github.com/Promact/oauth-client/tree/master/Promact.OAuth.Client/src/Promact.OAuth.Client.Test

**Comment by chintans** [comment]
are those integration tests or unit test?

**Comment by siddharthashw** [comment]
Ok..got the point. Need some time to analysis about this

**Comment by siddharthashw** [comment]
Start Date - 06/02/2017
Estimated Hours - 8 hours
End Date - 07/02/2017
