### ISSUE TITLE
Update README.md with relevant usage information

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-client#24]
Please update README.md on how to use oauth client. one of the example repositories is as follows.

https://github.com/Microsoft/Docker.DotNet

**Comment by siddharthashw** [comment]
Do I need to add changelog and licence details ??

**Comment by siddharthashw** [comment]
Start Date - 14/02/2017
Estimated Hours - 3 hours
End Date - 14/02/2017

**Comment by siddharthashw** [comment]
And Authors/Contributors to be listed ??
