### ISSUE TITLE
Create a utility to integrate it in oauth pipeline of Identity Framework.

### ISSUE THREAD

**Issue by siddharthashw** [Promact/oauth-client#3]
Need to create a utility to integrate it in OAuth pipeline of Identity Framework.

**Comment by siddharthashw** [comment]
Do we still need OAuth pipeline, as we have owin pipeline for this issue, in .net framework and OpenIdConnect pipeline in .net core.

@chintans sir suggested the way

**Comment by chintans** [comment]
The point of integration here is to have a logic to set Access Token or authorization token whichever token we are using to call API. It is not a specific OAuth flow.

**Comment by siddharthashw** [comment]
Start Date - 31/01/2017
Estimated Hours - 12 hours
End Date - 01/02/2017
